"""Add Promise Engine tables

Revision ID: 0f28bc9d4a52
Revises: 001_initial
Create Date: 2026-01-26 10:12:23.234814

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0f28bc9d4a52"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("agent_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("type", "id"),
    )
    op.create_index("idx_agents_type", "agents", ["type"], unique=False)
    op.create_table(
        "integrity_scores",
        sa.Column("agent_type", sa.String(length=50), nullable=False),
        sa.Column("agent_id", sa.String(length=100), nullable=False),
        sa.Column("vertical", sa.String(length=50), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("total_promises", sa.Integer(), nullable=True),
        sa.Column("kept_count", sa.Integer(), nullable=True),
        sa.Column("broken_count", sa.Integer(), nullable=True),
        sa.Column("renegotiated_count", sa.Integer(), nullable=True),
        sa.Column("pending_count", sa.Integer(), nullable=True),
        sa.Column("trust_capital", sa.Float(), nullable=True),
        sa.Column("recovery_rate", sa.Float(), nullable=True),
        sa.Column("avg_recovery_hours", sa.Integer(), nullable=True),
        sa.Column("trend_30d", sa.Float(), nullable=True),
        sa.Column("trend_90d", sa.Float(), nullable=True),
        sa.Column("vouching_strength", sa.Float(), nullable=True),
        sa.Column("vouched_by_count", sa.Integer(), nullable=True),
        sa.Column("vouching_accuracy", sa.Float(), nullable=True),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("agent_type", "agent_id", "vertical"),
    )
    op.create_index("idx_integrity_agent", "integrity_scores", ["agent_type", "agent_id"], unique=False)
    op.create_index("idx_integrity_score", "integrity_scores", ["overall_score"], unique=False)
    op.create_table(
        "journeys",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("agent_type", sa.String(length=50), nullable=False),
        sa.Column("agent_id", sa.String(length=100), nullable=False),
        sa.Column("vertical", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("outcome", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_journeys_agent", "journeys", ["agent_type", "agent_id"], unique=False)
    op.create_index(op.f("ix_journeys_agent_id"), "journeys", ["agent_id"], unique=False)
    op.create_index(op.f("ix_journeys_vertical"), "journeys", ["vertical"], unique=False)
    op.create_table(
        "promise_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("vertical", sa.String(length=50), nullable=False),
        sa.Column("promise_schema_id", sa.String(length=100), nullable=False),
        sa.Column("promise_version", sa.Integer(), nullable=False),
        sa.Column("promiser_type", sa.String(length=50), nullable=False),
        sa.Column("promiser_id", sa.String(length=100), nullable=False),
        sa.Column("promisee_type", sa.String(length=50), nullable=False),
        sa.Column("promisee_id", sa.String(length=100), nullable=False),
        sa.Column("input_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("violation_type", sa.String(length=100), nullable=True),
        sa.Column("violation_detail", sa.Text(), nullable=True),
        sa.Column("recovery_action", sa.String(length=100), nullable=True),
        sa.Column("recovery_outcome", sa.String(length=100), nullable=True),
        sa.Column("recovery_at", sa.DateTime(), nullable=True),
        sa.Column("user_confirmed", sa.Boolean(), nullable=True),
        sa.Column("user_feedback", sa.Text(), nullable=True),
        sa.Column("signal_strength", sa.String(length=20), nullable=True),
        sa.Column("touchpoint_id", sa.String(length=100), nullable=True),
        sa.Column("journey_id", sa.String(length=100), nullable=True),
        sa.Column("training_eligible", sa.Boolean(), nullable=True),
        sa.Column("exported_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_events_journey", "promise_events", ["journey_id"], unique=False)
    op.create_index("idx_events_pending", "promise_events", ["promiser_id", "result"], unique=False)
    op.create_index("idx_events_promisee", "promise_events", ["promisee_type", "promisee_id"], unique=False)
    op.create_index("idx_events_promiser", "promise_events", ["promiser_type", "promiser_id"], unique=False)
    op.create_index("idx_events_result", "promise_events", ["result"], unique=False)
    op.create_index("idx_events_schema", "promise_events", ["promise_schema_id"], unique=False)
    op.create_index("idx_events_touchpoint", "promise_events", ["touchpoint_id"], unique=False)
    op.create_index("idx_events_training", "promise_events", ["training_eligible", "exported_at"], unique=False)
    op.create_index(op.f("ix_promise_events_journey_id"), "promise_events", ["journey_id"], unique=False)
    op.create_index(op.f("ix_promise_events_promise_schema_id"), "promise_events", ["promise_schema_id"], unique=False)
    op.create_index(op.f("ix_promise_events_promiser_id"), "promise_events", ["promiser_id"], unique=False)
    op.create_index(op.f("ix_promise_events_promiser_type"), "promise_events", ["promiser_type"], unique=False)
    op.create_index(op.f("ix_promise_events_result"), "promise_events", ["result"], unique=False)
    op.create_index(op.f("ix_promise_events_timestamp"), "promise_events", ["timestamp"], unique=False)
    op.create_index(op.f("ix_promise_events_touchpoint_id"), "promise_events", ["touchpoint_id"], unique=False)
    op.create_index(op.f("ix_promise_events_training_eligible"), "promise_events", ["training_eligible"], unique=False)
    op.create_index(op.f("ix_promise_events_vertical"), "promise_events", ["vertical"], unique=False)
    op.create_table(
        "promise_schemas",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("vertical", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("commitment_type", sa.String(length=100), nullable=True),
        sa.Column("stakes", sa.String(length=20), nullable=True),
        sa.Column("schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verification_type", sa.String(length=50), nullable=True),
        sa.Column("verification_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("training_eligible", sa.Boolean(), nullable=True),
        sa.Column("domain_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deprecated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_schemas_active", "promise_schemas", ["deprecated_at"], unique=False)
    op.create_index("idx_schemas_vertical", "promise_schemas", ["vertical"], unique=False)
    op.create_index(op.f("ix_promise_schemas_vertical"), "promise_schemas", ["vertical"], unique=False)
    op.create_table(
        "touchpoints",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("vertical", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sequence_order", sa.Integer(), nullable=True),
        sa.Column("promise_schemas", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_touchpoints_vertical"), "touchpoints", ["vertical"], unique=False)
    op.create_table(
        "vouching",
        sa.Column("voucher_type", sa.String(length=50), nullable=False),
        sa.Column("voucher_id", sa.String(length=100), nullable=False),
        sa.Column("vouchee_type", sa.String(length=50), nullable=False),
        sa.Column("vouchee_id", sa.String(length=100), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("voucher_type", "voucher_id", "vouchee_type", "vouchee_id"),
    )
    op.create_index("idx_vouching_vouchee", "vouching", ["vouchee_type", "vouchee_id"], unique=False)
    op.create_index("idx_vouching_voucher", "vouching", ["voucher_type", "voucher_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_vouching_voucher", table_name="vouching")
    op.drop_index("idx_vouching_vouchee", table_name="vouching")
    op.drop_table("vouching")
    op.drop_index(op.f("ix_touchpoints_vertical"), table_name="touchpoints")
    op.drop_table("touchpoints")
    op.drop_index(op.f("ix_promise_schemas_vertical"), table_name="promise_schemas")
    op.drop_index("idx_schemas_vertical", table_name="promise_schemas")
    op.drop_index("idx_schemas_active", table_name="promise_schemas")
    op.drop_table("promise_schemas")
    op.drop_index(op.f("ix_promise_events_vertical"), table_name="promise_events")
    op.drop_index(op.f("ix_promise_events_training_eligible"), table_name="promise_events")
    op.drop_index(op.f("ix_promise_events_touchpoint_id"), table_name="promise_events")
    op.drop_index(op.f("ix_promise_events_timestamp"), table_name="promise_events")
    op.drop_index(op.f("ix_promise_events_result"), table_name="promise_events")
    op.drop_index(op.f("ix_promise_events_promiser_type"), table_name="promise_events")
    op.drop_index(op.f("ix_promise_events_promiser_id"), table_name="promise_events")
    op.drop_index(op.f("ix_promise_events_promise_schema_id"), table_name="promise_events")
    op.drop_index(op.f("ix_promise_events_journey_id"), table_name="promise_events")
    op.drop_index("idx_events_training", table_name="promise_events")
    op.drop_index("idx_events_touchpoint", table_name="promise_events")
    op.drop_index("idx_events_schema", table_name="promise_events")
    op.drop_index("idx_events_result", table_name="promise_events")
    op.drop_index("idx_events_promiser", table_name="promise_events")
    op.drop_index("idx_events_promisee", table_name="promise_events")
    op.drop_index("idx_events_pending", table_name="promise_events")
    op.drop_index("idx_events_journey", table_name="promise_events")
    op.drop_table("promise_events")
    op.drop_index(op.f("ix_journeys_vertical"), table_name="journeys")
    op.drop_index(op.f("ix_journeys_agent_id"), table_name="journeys")
    op.drop_index("idx_journeys_agent", table_name="journeys")
    op.drop_table("journeys")
    op.drop_index("idx_integrity_score", table_name="integrity_scores")
    op.drop_index("idx_integrity_agent", table_name="integrity_scores")
    op.drop_table("integrity_scores")
    op.drop_index("idx_agents_type", table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
